manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/dywj
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: yyz1
      import: app/west.yml
  self:
    path: config
